### ISSUE TITLE
Go Assembly by Example

### ISSUE THREAD

**Issue by pjebs** [mimoo/crypto_blogs#1]
Can you please put an example up for a situation where a function returns mutliple return values in Go?

Thank you in advance.

**Comment by mimoo** [comment]
I can probably do that, but as a quick explanation. See the first example.

```
MOVQ BX, ret+16(FP)
```

moves the quadword (64-bit) at register `BX` into `ret+16(FP)` which is the **F**rame **P**ointer with an offset of 16 bytes (2*8 bytes were used for the 2 arguments to the function).

So to have a second return value, you would have it 16+8 bytes from FP (since the first return value was of 8 bytes):

```
MOVQ BX, ret+16(FP)
MOVQ BX, ret+24(FP)
```

this would return two 64-bit arguments of the same value (BX, BX)
